version: '3.8'

services:
  nginx:
    container_name: next_nginx
    image: "nginx:1.17-alpine"
    restart: unless-stopped
    ports:
      - "8001:81"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend-app:/src/app/page
    depends_on:
      - next_app
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: "https://Way2Fun.com"

  next_app:
    image: next:alpine
    container_name: Way2Fun_app
    build:
      context: ./frontend-app
      dockerfile: dockerfiles/next.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/frontend-app
      - /frontend-app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8001
      -
